services:
    server:
        build: ./server
        networks: 
            -  webnet
        volumes: 
            - ./server:/app
        ports:
            - "8000:8000"
    client:
        build: ./client
        networks: 
            -  webnet
        volumes: 
            - ./client/:/app
            - ./client/node_modules:/app/node_modules
        environment:
            VITE_BACK_URL: http://localhost:8000
        ports:
            - "3000:3000"
networks:
    webnet:
