services:
    backend:
        build: ./server
        # image: byronoptiontest.azurecr.io/backend # para hacer deploy en azure
        ports:
            - "8000:8000"
    client:
        build: ./client
        # image: byronoptiontest.azurecr.io/client # para hacer deploy en azure
        ports:
            - "3000:3000"
    nginx:
        build: ./nginx
        # image: byronoptiontest.azurecr.io/nginx # para hacer deploy en azure
        depends_on:
            - backend
            - client
        restart: always
        ports:
            - "80:80"
